FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD postgres.jar /opt/postgres/
EXPOSE 8080
WORKDIR /opt/postgres/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "postgres.jar"]
